workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq-test2-python:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-test2-python
    orq-test2-prerelease-python:
        inputs:
            - location: ./openapi-prerelease.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-test2-prerelease-python
targets:
    orq-test2-python:
        target: typescript
        source: orq-test2-python
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-test2-python-code-samples
            blocking: false
    orq-test2-prerelease-python:
        target: typescript
        source: orq-test2-prerelease-python
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-test2-prerelease-python-code-samples
            blocking: false
